name: Build Optimized Kernel

on:
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Clone linux-cachyos and Patch
      run: |
        git clone https://github.com/CachyOS/linux-cachyos.git
        cd linux-cachyos
        curl -sL https://raw.githubusercontent.com/RikkaNekoo/mechrevo-wujie-15x-linux-cachyos/refs/heads/main/0001-modify.patch | patch -p1
        rm linux-cachyos/.SRCINFO

    - name: Run makepkg
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.9
      with:
        pkgdir: "./linux-cachyos/linux-cachyos"
        makepkgArgs: "-s --skipchecksum --noconfirm"

    - name: Upload Package Archive
      uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.makepkg.outputs.pkgfile0 }}

